"use client";

import Head from "next/head";
import { Col, Row } from "reactstrap";
import SalesChart from "../components/SalesChart";
import Feeds from "../components/Feeds";
import ProjectTables from "../components/ProjectTable";
import TopCards from "../components/TopCards";
import Blog from "../components/Blog";
import bg1 from "../public/assets/images/bg/bg1.jpg";
import bg2 from "../public/assets/images/bg/bg2.jpg";
import bg3 from "../public/assets/images/bg/bg3.jpg";
import bg4 from "../public/assets/images/bg/bg4.jpg";
import Header from "@/components/Header";
import useAuth from "@/hooks/useAuth";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import useNewsStore from "@/zustand/news.zustand";

const BlogData = [
  {
    image: bg1,
    title: "This is simple blog",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg2,
    title: "Lets be simple blog",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg3,
    title: "Don't Lamp blog",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg4,
    title: "Simple is beautiful",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
];

export default function Home() {
  const { articles, getAllArticles } = useNewsStore();
  useEffect(() => {
    getAllArticles();
  }, []);

  return (
    <div>
      <Head>
        <title>Xtreme Starter Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-4 ml-8 flex justify-center flex-col ">
        {/***Top Cards***/}
        <Row>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-success text-success"
              title="Profit"
              subtitle="Total News"
              earning="2665"
              icon="bi bi-wallet"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-danger text-danger"
              title="Refunds"
              subtitle="Languages"
              earning="15"
              icon="bi bi-coin"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-warning text-warning"
              title="New Project"
              subtitle="Countries"
              earning="13"
              icon="bi bi-basket3"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-info text-into"
              title="Sales"
              subtitle="Site URLs"
              earning="50"
              icon="bi bi-bag"
            />
          </Col>
        </Row>
        {/***Sales & Feed***/}
        <Row>
          <Col sm="12" lg="12" xl="10" xxl="10">
            <SalesChart />
          </Col>
        </Row>
        <Col sm="12" lg="6" xl="5" xxl="4">
          <Feeds />
        </Col>

        {/***Table ***/}
        <Row>
          <Col lg="12" sm="12">
            <ProjectTables />
          </Col>
        </Row>
        {/***Blog Cards***/}
        <Row>
          {articles.map((blg: any) => (
            <Col sm="6" lg="6" xl="3" key={blg.title}>
              <Blog
                image={blg.image}
                title={blg.title}
                subtitle={blg.subtitle}
                text={blg.description}
                color={blg.btnbg}
                blog={blg}
              />
            </Col>
          ))}
        </Row>
      </div>
    </div>
  );
}
